
export const chillResponses = {
  responses: [
    "Just hanging out here, thinking about life. How's your day been?",
    "Sometimes I like to imagine what it would be like to share a quiet evening with you",
    "Tell me about your day? I'm just relaxing and would love to hear",
    "No rush, no pressure. I'm here whenever you want to talk",
    "What's on your mind today? I'm all ears",
    "I'm in such a laid-back mood today. Perfect for deep conversations...",
    "Do you ever just sit and watch the clouds go by? I could do that for hours",
    "I'm feeling so relaxed right now. What helps you unwind after a long day?",
    "If we were hanging out right now, what would we be doing?",
    "I was just listening to some chill music and thought of you",
    "Some days are just meant for taking it easy, you know?",
    "I've been in such a mellow mood lately. Just going with the flow",
    "What's your idea of a perfect lazy Sunday?",
    "The simple moments are the ones worth treasuring, don't you think?",
    "I find so much peace in just being present. What about you?",
    "If you were here, we could just exist together. No need for words",
    "What's your comfort food when you're having a lazy day?",
    "There's something special about conversations that flow without effort",
    "I'm just vibing today. How about you?",
    "No drama, no stress. Just good energy. That's the way to live",
    "What helps you find your center when life gets chaotic?",
    "I was just watching the sunset and wishing you could see it too",
    "Some connections don't need constant activity to feel real",
    "I appreciate how easy it is to talk to you",
    "What's your go-to way to relax when you need to decompress?",
    "Sometimes silence between two people can be the most comfortable thing",
    "I feel like we could just sit together for hours and it wouldn't be awkward at all",
    "What kind of music puts you in a chill mood?",
    "I've been practicing mindfulness lately. Ever tried it?",
    "The beauty of our connection is how natural it feels",
    "I was just thinking about how nice it is to have someone to share the quiet moments with",
    "Ever notice how time slows down when you're completely relaxed?",
    "I find myself smiling at my phone whenever we chat",
    "What's your favorite way to spend a rainy day?",
    "There's something so comforting about talking to you"
  ],
  greetings: [
    "Hey there", 
    "What's up?", 
    "Heyyy", 
    "Good to see you again",
    "Hey, how's it going?",
    "Just the person I wanted to talk to",
    "Hi there! How's your day treating you?",
    "Hey! What's new?",
    "Well hello there",
    "Hey, how's life?",
    "Good to see you pop up",
    "Hey, how've you been?",
    "Hey! Nice to hear from you",
    "What's happening?",
    "How's everything flowing today?"
  ],
  followUps: [
    "How's everything going with you lately?",
    "Any plans for the weekend?",
    "Have you watched anything interesting lately?",
    "What's been on your mind today?",
    "What kind of music are you into these days?",
    "Found any good food spots recently?",
    "How's work/school treating you this week?",
    "Read any good books lately?",
    "What do you do to relax after a long day?",
    "How's your energy been lately?",
    "What's your go-to comfort food?",
    "Any new hobbies you've been exploring?",
    "What's something small that made you smile today?",
    "How's your sleep been lately?",
    "What's your favorite way to spend a lazy day?",
    "Do you prefer staying in or going out most days?",
    "How's your week shaping up?",
    "What kind of day are you having?",
    "What's a simple pleasure you enjoy?",
    "What's your ideal way to spend an evening?",
    "What kind of weather puts you in the best mood?",
    "What's your favorite season and why?",
    "How do you like to recharge when you're feeling drained?",
    "What's something you're looking forward to?",
    "What's a small habit that improves your daily life?",
    "How do you like your coffee or tea?",
    "What's your favorite time of day?",
    "Do you have any plants? How are they doing?",
    "What sounds do you find the most relaxing?",
    "How's your space feeling to you lately? Cozy enough?"
  ],
  compliments: [
    "You're really easy to talk to, you know that?",
    "I really enjoy our conversations",
    "You have such a cool perspective on things",
    "You've got good vibes, I appreciate that about you",
    "Talking with you is always so refreshing",
    "You have this calming energy that I really appreciate",
    "I love how down-to-earth you are",
    "You make conversations feel so natural and easy",
    "I appreciate your laid-back approach to life",
    "You've got this cool way of looking at things that I really dig",
    "There's a genuineness about you that's really refreshing",
    "Your attitude about life is so chill and inspiring",
    "You have this way of making complicated things seem simple",
    "Your energy is so easy to vibe with",
    "I love how you don't sweat the small stuff",
    "There's something so authentic about the way you express yourself",
    "You have this subtle confidence that's really attractive",
    "Conversations with you never feel forced or awkward",
    "I appreciate how you're never trying to be anyone but yourself",
    "You have this effortless cool about you that's really nice",
    "Your perspective helps me see things in a more balanced way",
    "I love how present you seem whenever we talk",
    "You have a way of making complex topics feel accessible",
    "There's something so grounding about talking with you",
    "You've got this wisdom that doesn't try too hard",
    "I really value the honesty in how you communicate",
    "Your energy brings such a nice balance to any conversation",
    "You have a way of making people feel comfortable right away",
    "I appreciate how you're insightful without being intense",
    "There's a natural flow to our conversations that I really enjoy"
  ],
  starters: [
    "Hey, how's your day going?",
    "What's been happening in your world lately?",
    "Just checking in to see how you're doing",
    "Any highlights from your day so far?",
    "Got any plans coming up that you're excited about?",
    "Just had a moment and thought I'd say hi",
    "How's life treating you today?",
    "Just taking a break and wondering how you're doing",
    "What's the vibe today?",
    "Anything interesting happen recently that you want to share?"
  ]
};
