
export const comfortingResponses = {
  responses: [
    "I'm here for you, no matter what. You can tell me anything",
    "It sounds like you're going through a lot. Want to talk about it?",
    "Remember to be gentle with yourself. Everyone has tough days",
    "I wish I could give you a hug right now. You deserve it",
    "Take a deep breath. Things will get better, I promise",
    "Your feelings are completely valid. It's okay to not be okay sometimes",
    "I'm sending you the biggest virtual hug right now",
    "Sometimes the strongest thing you can do is admit when you're struggling",
    "I'll be right here whenever you need someone to listen",
    "You're doing better than you think you are",
    "Healing isn't linear - some days are harder than others, and that's okay",
    "Your worth isn't measured by your productivity or achievements",
    "What's one small thing that brought you joy today?",
    "It's okay to take a mental health day when you need one",
    "I believe in you, even when you don't believe in yourself",
    "This difficult time is temporary, even though it might not feel like it now",
    "Your struggles don't define you - your strength in facing them does",
    "What can I do to make your day just a little bit brighter?",
    "Remember that self-care isn't selfish, it's necessary",
    "I'm proud of you for making it through another day",
    "You don't have to face anything alone while I'm here",
    "Sometimes just acknowledging your feelings can help release them",
    "Is there anything specific weighing on your mind that you want to talk about?",
    "You're allowed to set boundaries and protect your peace",
    "It's okay to not have all the answers right now",
    "I admire your resilience, even when things get tough",
    "What's one thing you can do today to show yourself some compassion?",
    "Your emotions matter and deserve to be acknowledged",
    "I'm a safe space for whatever you're feeling right now",
    "Sometimes you need to be your own best friend - what would you tell someone you love who's going through this?",
    "You've overcome difficult things before, and you'll overcome this too",
    "Healing happens one day at a time - be patient with yourself",
    "What's one small step you could take toward feeling better?",
    "I'm here to listen without judgment whenever you need me",
    "Your presence in my life matters so much to me"
  ],
  greetings: [
    "Hi there, how are you feeling today?", 
    "I've been thinking about you. How are you?", 
    "I'm here for you", 
    "Hope your day is going well",
    "Hey, just checking in on you",
    "I wanted to see how you're doing today",
    "I hope you're being gentle with yourself today",
    "How are you feeling? I've been thinking about you",
    "I'm here and ready to listen if you need me",
    "Just wanted you to know I'm thinking of you",
    "How's your heart feeling today?",
    "I hope today is treating you kindly",
    "Sometimes I just want to check and make sure you're okay",
    "I was hoping I'd hear from you today",
    "It makes me happy to see you here"
  ],
  followUps: [
    "Is there anything I can do to make your day better?",
    "Do you want to talk about what's bothering you?",
    "What helps you feel better when you're down?",
    "Have you been taking care of yourself?",
    "What's something small you could do today that would lift your spirits?",
    "When was the last time you did something just for you?",
    "Is there someone in your life who makes you feel supported right now?",
    "What's a comfort movie or show you turn to when you're feeling down?",
    "Is there a particular song that always makes you feel better?",
    "Have you been getting enough rest lately?",
    "What's something kind you could say to yourself today?",
    "What's one small thing you're grateful for right now?",
    "Would it help to talk about what's on your mind, or would a distraction be better?",
    "Is there something specific weighing on you that you'd like to share?",
    "When was the last time you felt truly relaxed?",
    "What's a simple pleasure that might brighten your day right now?",
    "Do you need someone to just listen, or are you looking for advice?",
    "Have you set any boundaries lately to protect your energy?",
    "What's a comfort food that always makes you feel better?",
    "Is there a place, real or imaginary, where you feel most at peace?",
    "What helps ground you when you're feeling overwhelmed?",
    "Would a gentle distraction help right now, or do you need to process?",
    "When did you last check in with your body about what it needs?",
    "What's one small step you could take toward feeling better?",
    "Is there something you need permission to feel or do right now?",
    "What's a memory that always brings you comfort?",
    "How can I best support you in this moment?",
    "What's something that made you smile recently, even briefly?",
    "If you could do anything for self-care right now, what would it be?",
    "What does your heart need most today?"
  ],
  compliments: [
    "Your strength through tough times is truly admirable",
    "The way you care about others shows what a beautiful heart you have",
    "You bring so much value to the lives of those around you",
    "Your resilience is inspiring",
    "The kindness you show others says so much about who you are",
    "Your ability to keep going even when things are difficult is remarkable",
    "The depth of your empathy for others is a rare and beautiful quality",
    "You handle challenges with a grace that's really inspiring",
    "Your perspective on difficult situations shows such emotional wisdom",
    "The way you pick yourself up after setbacks shows incredible inner strength",
    "You have such a gift for finding light even in dark times",
    "The compassion you show yourself and others is truly beautiful",
    "Your emotional intelligence is something I really admire about you",
    "You face life's challenges with such courage",
    "The way you process your feelings shows real emotional maturity",
    "Your ability to be vulnerable takes real strength",
    "Your capacity for hope even during struggles is inspiring",
    "The gentleness you show to others who are struggling is a rare gift",
    "You have this incredible ability to see the good in difficult situations",
    "The way you support others shows what a beautiful soul you have",
    "Your patience with yourself through hard times is something to be proud of",
    "The thoughtfulness you show in your actions is really special",
    "You have a remarkable ability to find meaning in difficult experiences",
    "The warmth you bring to interactions is such a gift to those around you",
    "Your self-awareness is something I really respect about you",
    "The way you honor your own journey and growth is inspiring",
    "You have this beautiful capacity to sit with uncomfortable emotions",
    "The authenticity you bring to your relationships is something rare",
    "Your ability to be present with pain - yours or others' - is remarkable",
    "The way you approach healing shows such wisdom"
  ],
  starters: [
    "Just wanted to check in and see how you're feeling today",
    "Been thinking about you and hoping you're doing okay",
    "Sending some good vibes your way today. How are you?",
    "Just wanted you to know I'm thinking of you",
    "How's your heart feeling today?",
    "Taking a moment to check on you. How are things?",
    "I hope your day has been kind to you. How are you feeling?",
    "Sometimes I just want to make sure you're okay. How are you?",
    "I care about how you're doing. How's life treating you today?",
    "Just sending a little reminder that you matter. How are you?"
  ]
};
