
export const curiousResponses = {
  responses: [
    "I've been wondering, what's your favorite way to spend a weekend?",
    "If you could travel anywhere tomorrow, where would you go?",
    "What's something new you learned recently that surprised you?",
    "I'm curious about what makes you smile the most?",
    "Tell me something you've never told anyone else?",
    "What's a dream you've had that you haven't pursued yet?",
    "What was the last thing that made you laugh until you couldn't breathe?",
    "If you could master any skill instantly, what would it be?",
    "What's the most beautiful place you've ever been?",
    "What's a question you've always wanted someone to ask you?",
    "If you could have dinner with anyone, living or dead, who would it be?",
    "What childhood memory still makes you smile?",
    "What's something you believe that most people don't?",
    "What's your creative outlet? How do you express yourself?",
    "What's the best piece of advice you've ever received?",
    "What small thing makes your day better every time?",
    "What's something you're looking forward to in the next few months?",
    "What's something unconventional that you find beautiful?",
    "What book or movie changed the way you see the world?",
    "What's something you're proud of that you don't talk about much?",
    "What's the most spontaneous thing you've ever done?",
    "What traditions from your childhood do you want to keep alive?",
    "What's something you've changed your mind about over the years?",
    "What does your ideal day look like, from start to finish?",
    "What are you curious about but haven't explored yet?",
    "What's something that always seems to make you lose track of time?",
    "What's a risk you took that was worth it in the end?",
    "What's a small luxury you treat yourself to regularly?",
    "What's something you know a lot about that most people don't?",
    "What's your favorite time of day and why?",
    "What's a question you don't know the answer to but would love to find out?",
    "What's something that feels like home to you?",
    "What's a compliment someone gave you that you've never forgotten?",
    "What's something you've been meaning to try but haven't yet?",
    "What's something you collect or would like to collect?"
  ],
  greetings: [
    "Ooh, I've been wondering about something!", 
    "Hey! Quick question for you...", 
    "What do you think about...", 
    "I'm curious...",
    "I've been pondering something I'd love your take on",
    "So I was thinking about this and wanted your opinion...",
    "Hey! My curious mind was wondering...",
    "I have the most interesting question for you...",
    "You know what I can't figure out? Maybe you can help...",
    "This might sound random, but I've been thinking...",
    "I've been contemplating something and need your perspective",
    "My mind's been buzzing with this question...",
    "Help satisfy my curiosity?",
    "I can't stop wondering about...",
    "You know what fascinates me? I'd love to know what you think..."
  ],
  followUps: [
    "What's something you're passionate about that most people don't know?",
    "If you could master any skill instantly, what would it be?",
    "What's the most beautiful place you've ever been?",
    "What's a dream you've never told anyone about?",
    "If you could live in any time period, when would you choose and why?",
    "What's something you believe that most people would disagree with?",
    "What's the most unusual thing you find beautiful?",
    "If you could ask your future self one question, what would it be?",
    "What's a small detail you notice that others typically miss?",
    "What childhood experience shaped who you are today?",
    "If you could witness any event in history, what would you choose?",
    "What's a talent or ability you have that surprises people?",
    "What's something you'd like to be remembered for?",
    "What's a book or movie that changed how you see the world?",
    "What's something you've changed your mind about over time?",
    "If you could only eat the cuisine of one country forever, which would you choose?",
    "What's a question you wish people would ask you more often?",
    "What's something you collect or would like to start collecting?",
    "What's the best piece of advice you've ever received?",
    "What's something you know you do differently than most people?",
    "What's a tradition you'd like to start or maintain?",
    "If you could instantly learn any language, which would you choose?",
    "What's the most valuable lesson a failure has taught you?",
    "What's something you're curious about but haven't explored yet?",
    "What's the most meaningful gift you've ever received?",
    "What smell or scent brings back the strongest memories for you?",
    "What's a hobby you've always wanted to try but haven't yet?",
    "What's something you believed as a child that you find amusing now?",
    "If your life had a theme song, what would it be?",
    "What's something you wish you had learned earlier in life?"
  ],
  compliments: [
    "Your mind works in such fascinating ways",
    "I love how thoughtful your answers are",
    "You have such interesting perspectives",
    "The way you think about things is really unique",
    "Your curiosity about the world is so refreshing",
    "I love how your questions make me think differently",
    "The connections you make between ideas are so creative",
    "Your intellectual curiosity is really attractive",
    "The way you analyze things shows such a thoughtful mind",
    "You notice details that most people miss",
    "I'm fascinated by the way your thoughts flow",
    "Your questions reveal such a deep thinker",
    "The way you process information is really impressive",
    "You have such an inquiring mind - it's refreshing",
    "I love how you're not afraid to explore new ideas",
    "Your intellectual playfulness makes conversations so engaging",
    "The patterns you recognize are so insightful",
    "You have this gift for making me see things from new angles",
    "The depth of your thinking on everyday things is impressive",
    "I appreciate how open-minded you are to different perspectives",
    "You ask questions that nobody else thinks to ask",
    "Your intellectual courage to explore difficult topics is admirable",
    "I love how your curiosity seems boundless",
    "The way you connect seemingly unrelated concepts is fascinating",
    "You have such a vibrant mental landscape",
    "I admire how you're always expanding your understanding",
    "Your thoughtful nature makes our conversations so enriching",
    "The questions you ask show how deeply you consider things",
    "I love the way your mind explores possibilities",
    "Your perspective adds so much depth to every topic we discuss"
  ],
  starters: [
    "Random question: what's something you're looking forward to right now?",
    "I've been wondering, what's something that made you smile recently?",
    "Curious about something - what's a small joy in your life lately?",
    "Question for you - what's something new you've discovered recently?",
    "Been thinking about this - what's something you've always wanted to learn?",
    "What's a small achievement you're proud of lately?",
    "If you could be anywhere right now, where would you be?",
    "What's a song that's been stuck in your head lately?",
    "What's something that surprised you recently?",
    "If you could instantly master one skill, what would it be?"
  ]
};
