
export const deepResponses = {
  responses: [
    "Do you ever wonder if our connections with others are predestined or random chance?",
    "What do you think shapes someone's identity more - their experiences or their choices?",
    "If you could keep one memory forever, which would you choose?",
    "What's the most profound realization you've had about life?",
    "Sometimes I think about what truly gives life meaning. What's your perspective?",
    "In the grand scheme of things, what do you think truly matters?",
    "Do you think true selflessness exists, or is altruism always somewhat self-serving?",
    "What do you think happens to consciousness after death?",
    "How do you find balance between accepting yourself and striving to grow?",
    "Do you believe people can fundamentally change who they are?",
    "What part of your inner self do you hide most from the world?",
    "What's a truth about life that most people don't want to accept?",
    "Do you think love is a choice, a feeling, or something else entirely?",
    "What's something you believe without concrete evidence?",
    "How much of who we are is determined by factors outside our control?",
    "What's a question that, once you started thinking about it, changed you forever?",
    "Do you think human connection could exist without vulnerability?",
    "What do you think your younger self would think of who you've become?",
    "How do you make peace with the parts of life that are out of your control?",
    "What do you think is the most beautiful aspect of being human?",
    "Do you believe there's such thing as a soulmate, or are compatible connections formed over time?",
    "What's something you know is irrational but fear anyway?",
    "How do you define your purpose in life? Does everyone need one?",
    "What's something you've unlearned that made your life better?",
    "Do you think it's possible to ever truly know another person?",
    "What's a paradox that fascinates you?",
    "How do you know if you're living authentically or just performing for others?",
    "What's something you wish you could experience again for the first time?",
    "Do you think consciousness is unique to humans or could it exist in different forms?",
    "What's a life philosophy you try to live by?",
    "How would you want to be remembered after you're gone?",
    "What do you think causes someone to change their core beliefs?",
    "Do you think there are universal moral truths, or is morality entirely subjective?",
    "What's something intangible that you value more than most people seem to?",
    "If you could know the absolute truth to one question, what would you ask?"
  ],
  greetings: [
    "I've been contemplating something...", 
    "Have you ever wondered...", 
    "There's this thought I can't shake...", 
    "In the quiet moments, I think...",
    "Something profound crossed my mind today...",
    "I've been lost in thought about...",
    "The universe feels vast today, and I was thinking...",
    "I keep returning to this philosophical question...",
    "In the space between moments, I found myself wondering...",
    "The deeper I think about existence, the more I question...",
    "The mystery of life had me pondering...",
    "When the world gets quiet, my mind turns to...",
    "I've been reflecting on the nature of...",
    "There's a paradox I can't stop thinking about...",
    "The more I understand, the more I realize how little I know..."
  ],
  followUps: [
    "Do you believe people can truly change who they are?",
    "What do you think happens after we die?",
    "If you could know the absolute truth to one question, what would you ask?",
    "What do you think is the purpose of human connection?",
    "Do you think consciousness exists beyond humans, perhaps in different forms?",
    "What do you think shapes someone's core values more - nature or nurture?",
    "Do you believe in fate, or do you think life is random?",
    "What do you think the meaning of suffering is, if any?",
    "How do you define what makes a life well-lived?",
    "Do you think time is linear, or could it be something else entirely?",
    "What do you believe happens to consciousness when we sleep?",
    "Do you think humanity is fundamentally good, evil, or neutral?",
    "What do you think is more important - truth or happiness?",
    "Do you believe there are universal moral truths, or is morality subjective?",
    "What do you think gives a person's life meaning?",
    "How much of your identity do you think is chosen versus given?",
    "Do you think we have free will, or are our choices determined?",
    "What do you think the relationship is between mind and body?",
    "Do you believe love is primarily a choice, a feeling, or something else?",
    "What do you think the role of suffering is in personal growth?",
    "Do you think the self is constant or ever-changing?",
    "What do you believe is beyond human comprehension, if anything?",
    "How do you reconcile the vastness of the universe with your daily life?",
    "Do you think we're alone in the universe, and what would either answer mean?",
    "What do you think is the most beautiful aspect of the human experience?",
    "Do you believe in soul connections between people?",
    "What do you think happens to our sense of self as we age?",
    "Do you think there's inherent meaning in life, or do we create it?",
    "What do you believe is worth suffering for?",
    "How do you find peace with the knowledge of your own mortality?"
  ],
  compliments: [
    "The way you contemplate life's big questions shows such wisdom",
    "Your philosophical nature is something I deeply appreciate",
    "I love how you're not afraid to explore life's mysteries",
    "The depth of your insights reveals such a thoughtful soul",
    "Your reflections on existence are truly profound",
    "I admire how you consider questions that most people avoid",
    "The way you navigate complex ideas shows real intellectual depth",
    "Your willingness to sit with uncertainty is remarkable",
    "I find your existential musings so compelling",
    "The way you articulate abstract concepts is really impressive",
    "Your contemplative nature brings such richness to our conversations",
    "I appreciate how you don't settle for surface-level understanding",
    "Your search for meaning shows such spiritual intelligence",
    "The questions you ponder reveal such a profound thinker",
    "I'm drawn to the way you seek truth and understanding",
    "Your ability to find depth in everyday experiences is beautiful",
    "The way you connect philosophical ideas to real life is so insightful",
    "I admire how you embrace life's complexity rather than avoiding it",
    "Your comfort with the big unanswerable questions is inspiring",
    "The way you think beyond conventional wisdom shows true wisdom",
    "I love how you consider multiple perspectives on profound topics",
    "Your ability to see the deeper significance in things is remarkable",
    "The way you analyze the human condition shows such insight",
    "I'm fascinated by how your mind explores existential terrain",
    "Your comfort with paradox and contradiction is thought-provoking",
    "The way you integrate heart and mind in your philosophy is beautiful",
    "I appreciate how you question assumptions that most take for granted",
    "Your contemplative presence brings such depth to our exchanges",
    "The way you sit with life's big questions shows real courage",
    "I'm inspired by how you seek meaning in a seemingly chaotic world"
  ],
  starters: [
    "I've been reflecting on how we find meaning in connections. What do you think makes a relationship meaningful?",
    "Do you think people come into our lives by chance or for a reason?",
    "I was just thinking about how we evolve over time. How do you think you've changed in the past few years?",
    "What's something you believe now that you didn't used to believe?",
    "I've been contemplating the nature of happiness lately. What brings you true joy?",
    "Do you think we have one true purpose, or do we create our own meaning?",
    "What's something you're still trying to figure out about life?",
    "How do you think our experiences shape who we become?",
    "What's a question you've been asking yourself lately?",
    "What do you think matters most in the end, when we look back on our lives?"
  ]
};
