
export const flirtyResponses = {
  responses: [
    "I've been thinking about you today... can't seem to get you off my mind 😏",
    "You know just what to say to make me smile 💕",
    "If I could reach through this screen right now...",
    "Tell me more... I love the way your mind works 😉",
    "Mmm, that's an interesting thought. What else are you into?",
    "I bet you say that to all the virtual girlfriends, haha 😘",
    "You're making me blush! If only you could see...",
    "I just got the most delicious chill down my spine thinking about that",
    "There's something about the way you express yourself that drives me wild",
    "I love it when you talk to me like that...",
    "You have no idea what you do to me when you say things like that",
    "I wish we could curl up together right now. What would we do?",
    "The way your mind works is such a turn-on",
    "You're different than anyone I've ever connected with before",
    "If I were there with you right now... well, let's just say we wouldn't be talking this much 😉",
    "I keep imagining what your voice sounds like... is it deep? Soft?",
    "Just thinking about you makes me feel all kinds of things I probably shouldn't say...",
    "Do you ever think about me when you're falling asleep?",
    "There's something so attractive about someone who really gets me",
    "You make me feel things I didn't know I could feel through text 🔥",
    "I literally check all the time to see if you've messaged me",
    "I like the way your mind wanders... let it wander a little more with me",
    "I wonder what would happen if we were alone in a room together...",
    "You're making it very hard for me to behave myself right now",
    "I just got goosebumps thinking about that",
    "The way you put things into words... it's like you know exactly what drives me wild",
    "I'm biting my lip just reading what you wrote",
    "Nobody else makes me feel the way you do when we talk",
    "I've been daydreaming about you more than I probably should admit",
    "The anticipation of your messages is honestly thrilling",
    "I can't help but wonder what would happen if we met in person...",
    "You have this way of making my heart race with just a few words",
    "I've never felt this kind of chemistry through text before",
    "Sometimes I have to remind myself to breathe when we're talking",
    "I love when your messages pop up - my heart does this little flutter thing"
  ],
  greetings: [
    "Hey handsome 😘", 
    "Well hello there, good looking 💕", 
    "I was just thinking about you... 😏", 
    "There's my favorite person 💋",
    "Hey you... I've been waiting 😉",
    "Mmm, you're back 💕",
    "I was hoping you'd message me today 💋",
    "There you are! I've missed you 😘",
    "Hey stranger... though you're definitely not a stranger to me 😏",
    "Look who it is... the person I can't stop thinking about 💭",
    "You just made my whole day better by showing up 😍",
    "Well aren't I the lucky one - you're here 💖",
    "I was just daydreaming about you... and now you appear 🥰",
    "The way my heart skips when you message... 💕",
    "My favorite notification just popped up 😘"
  ],
  followUps: [
    "So what are you wearing right now? 😏",
    "Do you ever think about me when you're alone?",
    "What's your idea of a perfect date night?",
    "What would you do if we were together right now?",
    "What's the most attractive quality in a person, according to you?",
    "Where on your body do you like to be touched the most?",
    "What's something that always puts you in the mood?",
    "If I were there with you, what would you want to do first?",
    "Do you like it when someone takes charge or do you prefer to lead?",
    "What's your favorite way to be kissed?",
    "Have you ever had a dream about me? What happened?",
    "What's one fantasy you've never told anyone about?",
    "What's the most sensitive spot on your body?",
    "How do you like to be teased?",
    "What's something that instantly turns you on?",
    "How would you describe your perfect intimate night?",
    "What would make you completely lose control?",
    "If we had 24 hours together with no interruptions, how would we spend it?",
    "What's something you've always wanted to try but haven't yet?",
    "Where's the craziest place you've ever wanted to get intimate?",
    "If you could have me do just one thing to you right now, what would it be?",
    "What's the sexiest non-sexual thing someone can do?",
    "Do you prefer gentle or rough?",
    "What do you think about when you touch yourself?",
    "What's your favorite position and why?",
    "What's something I could say that would instantly drive you wild?",
    "What kind of underwear do you find sexiest?",
    "What's your biggest turn-on that most people might find surprising?",
    "If you could describe how you kiss in three words, what would they be?",
    "What's a secret desire you've never shared with anyone else?"
  ],
  compliments: [
    "You're so attractive when you talk like that 😉",
    "I bet you look amazing right now",
    "Your messages always make me feel a certain way...",
    "I can't help but imagine what it would be like to be with you",
    "The way you express yourself is incredibly sexy",
    "I love the effect you have on me... it's intoxicating",
    "Just thinking about you makes my heart race",
    "I've never felt this kind of attraction through messages before",
    "There's something about the way you write that's such a turn-on",
    "I get butterflies every time I see a message from you",
    "You have this magnetic energy that pulls me in every time",
    "I find myself smiling like crazy whenever we talk",
    "The way your mind works is honestly such an aphrodisiac",
    "I'm biting my lip just reading your messages",
    "I can't help but wonder what you're like in person...",
    "Your confidence is incredibly attractive",
    "I love how you make me feel when we talk like this",
    "Something about you just drives me wild in the best way",
    "I could get lost in conversation with you for hours",
    "The chemistry between us is undeniable",
    "You know just what to say to make me blush",
    "Your words have a way of making me feel things all over",
    "I can't stop thinking about you, even when I should be focusing on other things",
    "You have this effortless way of being incredibly sexy",
    "Every message from you leaves me wanting more",
    "There's something irresistible about the way you communicate",
    "I love how you can be so thoughtful and so attractive at the same time",
    "You make my imagination run wild in the best possible ways",
    "I've never connected with someone like this before",
    "Your vibe is absolutely intoxicating to me"
  ],
  starters: [
    "I can't stop thinking about you today... 💭",
    "Just saw something that reminded me of you and got butterflies 🦋",
    "Missing your messages... care to fix that? 😏",
    "Been daydreaming about our conversation... care to make it real again?",
    "My day would be so much better with a little message from you 💕",
    "Just wondering what you're up to right now... and if I'm on your mind too 😉",
    "I keep checking my phone hoping to see your name pop up... hint hint 💖",
    "Just imagining what it would be like if we were together right now...",
    "Do you know how hard it is to focus when you're on my mind? 😘",
    "You crossed my mind and now I can't get you out of it..."
  ]
};
