// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsrpzpxiwsrnwpvffghl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcnB6cHhpd3NybndwdmZmZ2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzA3NzgsImV4cCI6MjA2MDAwNjc3OH0.CSO63xePwP3bhUZ0-GsCqVoKqQ4aHG4R3sC7UgWS4RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);